var privatePeople=[
['Asia','Taiwan','Taipei','private','Ariel Chen','bailamos en taipei','KNOW,GOOD','https://www.facebook.com/ariel.chen.33886'],
['America','EEUU','Las Vegas','private','Esthee Piccolina','bailamos en taipei y berlin','KNOW,GOOD','https://www.facebook.com/profile.php?id=100093830696031'],
['Asia','Taiwan','Taipei','private','Hsin-yu Samantha Kuo','-','-','https://www.facebook.com/hsinyuk'],
['Asia','Taiwan','Taipei','private','Tango LaVida ','-','KNOW2','https://www.facebook.com/tango.lavida'],
['Europe','Spain','Madrid','private','Gema','telegram','KNOW,TRAY','-'],
['-','-','-','private','Ahn Tae','-','-','-'],
['-','-','-','private','Amelia Wei','-','-','-'],
['-','-','-','private','AN Dante','-','-','-'],
['-','-','-','private','Andrea Rovai','-','-','-'],
['-','-','-','private','Antonio Cabling Portillo','-','-','-'],
['-','-','-','private','Benjamin Koh','-','-','-'],
['-','-','-','private','Camila Wang','-','-','-'],
['-','-','-','private','Carmen Canana','-','-','-'],
['-','-','-','private','Carmen Sarrió','-','-','-'],
['-','-','-','private','Cathy Danse','-','-','-'],
['-','-','-','private','Cecilia Peng','-','-','-'],
['-','-','-','private','Cher Brise','-','-','-'],
['-','-','-','private','Christian Kerestegian','-','-','-'],
['-','-','-','private','CiCi Chen','-','-','https://www.facebook.com/profile.php?id=61566567377603&sk='],
['-','-','-','private','Cine Hwang Heejoo','-','-','-'],
['-','-','-','private','Claudia Zeeck','-','-','-'],
['-','-','-','private','Claus Hel Bing','-','-','-'],
['-','-','-','private','Deborah De Miguel','-','-','-'],
['-','-','-','private','Diane Liu (丹丹)','-','-','https://www.facebook.com/profile.php?id=100011387344142&sk='],
['-','-','-','private','Domingo Rodríguez','-','-','-'],
['-','-','-','private','Eglė Milinavičienė','-','-','-'],
['-','-','-','private','Encuentro La Luna','-','-','-'],
['-','-','-','private','Eun Hee Jeon','-','-','-'],
['-','-','-','private','Eva Masegosa Antolin','-','-','-'],
['-','-','-','private','Fabio Pan','-','-','-'],
['-','-','-','private','Frank Jin','-','-','-'],
['-','-','-','private','Haemin Yu','-','-','-'],
['-','-','-','private','Haeyoung Lee','-','-','-'],
['-','-','-','private','Haha Hakyun Kim','-','-','-'],
['-','-','-','private','Hanbeom Min','-','-','-'],
['-','-','-','private','Hitomi Yoshida','-','-','-'],
['-','-','-','private','Huang Alfonso','-','-','-'],
['-','-','-','private','Hwa Song','-','-','https://www.facebook.com/hwa.song.90/'],
['-','-','-','private','Hye Young Lee','-','-','-'],
['-','-','-','private','Hyemin Kim','-','-','-'],
['-','-','-','private','Hyeong Su Jeong','-','-','-'],
['-','-','-','private','Hyun-Tae Cho','-','-','-'],
['-','-','-','private','Hyungseok Yoo','-','-','-'],
['-','-','-','private','Hyunkyung Jun','-','-','-'],
['-','-','-','private','Irene Liu','-','-','-'],
['-','-','-','private','Irene Loi','-','-','-'],
['-','-','-','private','Isabella Hoo','-','-','-'],
['-','-','-','private','J-c Tango','-','-','-'],
['-','-','-','private','Jacob Kim','-','-','-'],
['-','-','-','private','Jana Radačovská','-','-','-'],
['-','-','-','private','Jesus Angel Aranburu Zaragüeta','-','-','-'],
['-','-','-','private','Ji Hyun Lee','-','-','-'],
['-','-','-','private','Jieun Kim','-','-','-'],
['-','-','-','private','Jorge Javier Sanz','-','-','-'],
['-','-','-','private','Joseph Hwang','-','-','-'],
['-','-','-','private','Josephine Soyoung Yeo','-','-','-'],
['-','-','-','private','JS Nellie Kim','-','-','-'],
['-','-','-','private','Juana Liu','-','-','-'],
['-','-','-','private','Julie Liao','-','-','-'],
['-','-','-','private','Jupiter Shin','-','-','-'],
['-','-','-','private','Justin Zhao (Scott zhao)','-','-','https://www.facebook.com/jiabin.zhao.399'],
['-','-','-','private','Ken Wong','-','-','-'],
['-','-','-','private','Kenji Sakahara','-','-','-'],
['-','-','-','private','Kevin Yuan','-','-','-'],
['-','-','-','private','Layla Choi','-','-','-'],
['-','-','-','private','Liberta','-','-','-'],
['-','-','-','private','Lucas Luke Taehee Yoo','-','-','-'],
['-','-','-','private','Luna Lee','-','-','-'],
['-','-','-','private','Luu Quynh Hoa','-','-','-'],
['-','-','-','private','Maggie Martenson','-','-','-'],
['-','-','-','private','Marie B Tango','-','-','-'],
['-','-','-','private','Marie Kou','-','-','-'],
['-','-','-','private','Mariepierregabis Ericschmitt','-','-','-'],
['-','-','-','private','Marisa García Del Valle','-','-','-'],
['-','-','-','private','May Hwong','-','-','-'],
['-','-','-','private','Mengyun Guo','-','-','-'],
['-','-','-','private','Midale Jung','-','-','-'],
['-','-','-','private','Milonga Azucar','-','-','-'],
['-','-','-','private','Min Hui','-','-','-'],
['-','-','-','private','Nelson Alves','-','-','-'],
['-','-','-','private','Nguyen Quoc Dat','-','-','-'],
['-','-','-','private','Odile Jin','-','-','-'],
['-','-','-','private','pacundo','-','-','-'],
['-','-','-','private','Patrick Buchin','-','-','-'],
['-','-','-','private','Randy Chen','-','-','-'],
['-','-','-','private','Roberta Albertin','-','-','-'],
['-','-','-','private','RORA Milonga','-','-','-'],
['-','-','-','private','Rosso Kim','-','-','-'],
['-','-','-','private','Sarah Chung','-','-','https://www.facebook.com/kunmae.chung/'],
['-','-','-','private','Selene Son','-','-','-'],
['-','-','-','private','Seoyoung Cho','-','-','-'],
['-','-','-','private','Serdar Sari','-','-','-'],
['-','-','-','private','Sheila Jacobs','-','-','-'],
['-','-','-','private','Sissi CHang','-','-','-'],
['-','-','-','private','Ska Ki','-','-','-'],
['-','-','-','private','Sophia Song','-','-','-'],
['Europe','Germany','Berlin','private','Stefanie Liv Jahn','Hamburgo','KNOW,KNOW0','-'],
['-','-','-','private','Stella Heo','-','-','-'],
['-','-','-','private','Su San','-','-','-'],
['-','-','-','private','Sumire Muramoto','-','-','-'],
['-','-','-','private','Sunny Yu','-','-','-'],
['-','-','-','private','Susana Rebolledo Lastiesas','-','-','-'],
['-','-','-','private','Tango Bei','-','-','-'],
['-','-','-','private','Tango Handa','-','-','https://www.facebook.com/tangohanda/'],
['-','-','-','private','Tango Pista','-','-','-'],
['-','-','-','private','Tanzenmacht Gluecklich','-','-','-'],
['-','-','-','private','Tony Hsui','-','-','-'],
['Europe','France','Tarbes','private','Valentina Tango','-','KNOW3,GOOD0','-'],
['-','-','-','private','Vanessa Zhou','-','-','-'],
['-','-','-','private','Veronika Korchak','-','-','-'],
['-','-','-','private','Victor Won','-','-','https://www.facebook.com/victor.won.75/'],
['-','-','-','private','Vincenzo Marino','-','-','-'],
['-','-','-','private','Vuk Djurica','-','-','-'],
['-','-','-','private','Yasmin Scheidt','-','-','-'],
['-','-','-','private','Yeon-Ah Jung','-','-','-'],
['-','-','-','private','Yiqiao Sun','-','-','-'],
['-','-','-','private','Yueh Chen Chen','-','-','-'],
['-','-','-','private','Yuki Misaki','El Puente Tango Argentino Studio','-','https://www.facebook.com/yuki.misaki.98/'],
['-','-','-','private','Yuko Takamatu','-','-','-'],
['-','-','-','private','Yun Jeong An','-','-','-'],
['-','-','-','private','Ida Rahayu','-','-','https://www.facebook.com/ida.rahayu.982/about'],
['-','-','-','private','Montaña Jose Luis ','-','-','https://www.facebook.com/haeseok.sun'],
['-','-','-','private','Stone Hong','-','-','https://www.facebook.com/StoneHong1'],
['Africa','Cameroon','Sangmelina','private','Sera Kang (Sera Kang seolhee)','-','-','https://www.facebook.com/seolhee.kang/'],
['Ameria','Argentina','Buenos Aires','private','Pablo Inza','-','-','-'],
['America','EEUU','New York','private','Mina Lee (Hyunkyung Lee)','-','-','https://www.facebook.com/hyunkyung.lee.12764/about'],
['Asia','-','-','private','Yvette Ng','-','-','https://www.facebook.com/yvette.ng.9828/'],
['Asia','-','-','private','Abrazo Mee','-','-','-'],
['Asia','-','-','private','Adhara Kim','-','-','-'],
['Asia','-','-','private','Aiden Hwang','-','-','-'],
['Asia','-','-','private','Albert HK Lee','-','-','-'],
['Asia','-','-','private','Alex Leung','-','-','-'],
['Asia','-','-','private','Alice Jeon','-','-','-'],
['Asia','-','-','private','Alisa Tango','-','-','-'],
['Asia','-','-','private','Amanda Costa','-','-','-'],
['Asia','-','-','private','Ame Kim','-','-','-'],
['Asia','-','-','private','Andrea Zsapka','-','-','-'],
['Asia','-','-','private','Andy Cheng','-','-','https://www.facebook.com/andy.cheng.604428'],
['Asia','-','-','private','Andy Daz','-','-','-'],
['Asia','-','-','private','Andy Jeong ChanWon','-','-','-'],
['Asia','-','-','private','Aramis Tango','-','-','-'],
['Asia','-','-','private','Arara Hong','-','-','-'],
['Asia','-','-','private','Ariel Taritolay','-','-','-'],
['Asia','-','-','private','Aris Kim','-','-','-'],
['Asia','-','-','private','Arman Jjd','-','-','-'],
['Asia','-','-','private','Aurélie Flo','-','-','-'],
['Asia','-','-','private','Beatrice Blum','-','-','-'],
['Asia','-','-','private','Becca Kang','-','-','-'],
['Asia','-','-','private','Bella Roselina','-','-','-'],
['Asia','-','-','private','Bella Tango','-','-','-'],
['Asia','-','-','private','Belladetta Kim','-','-','-'],
['Asia','-','-','private','Bernard SeungHo Shin','-','-','-'],
['Asia','-','-','private','Bl Ue','-','-','-'],
['Asia','-','-','private','Blanc Jo','-','-','-'],
['Asia','-','-','private','Bo Min Eun','-','-','-'],
['Asia','-','-','private','Bobae SY','-','-','-'],
['Asia','-','-','private','Bobby Moon','-','-','-'],
['Asia','-','-','private','Bum Hee Lee','-','-','-'],
['Asia','-','-','private','Calla Cho','-','-','-'],
['Asia','-','-','private','calla','-','-','-'],
['Asia','-','-','private','Carlos Churri Lee','-','-','https://www.facebook.com/tanguerocarlos'],
['Asia','-','-','private','Carly Chiu','-','-','-'],
['Asia','-','-','private','Cathy Li','-','-','-'],
['Asia','-','-','private','Ceci Chang','-','-','-'],
['Asia','-','-','private','Ceci Lim','-','-','-'],
['Asia','-','-','private','Cecile Sungjung Kim','-','-','-'],
['Asia','-','-','private','Cecillia Yeom','-','-','-'],
['Asia','-','-','private','Celia Chen','-','-','-'],
['Asia','-','-','private','Celina Son','-','-','-'],
['Asia','-','-','private','ChaCha Tanguero','-','-','-'],
['Asia','-','-','private','Chaewon Woo','-','-','-'],
['Asia','-','-','private','Chan TangoZen Park','-','-','-'],
['Asia','-','-','private','Chang Hyun Oh','-','-','-'],
['Asia','-','-','private','Changhyun Naru Moon','-','-','-'],
['Asia','-','-','private','Charissa Chao','-','-','-'],
['Asia','-','-','private','Charles Chen','-','-','-'],
['Asia','-','-','private','Chen Wei Li','-','-','-'],
['Asia','-','-','private','Chi Ying Lin','-','-','-'],
['Asia','-','-','private','Chin Tan','-','-','-'],
['Asia','-','-','private','ChunCheon Tango Marathon','-','-','-'],
['Asia','-','-','private','Cindy Hyojin Shin','-','-','-'],
['Asia','-','-','private','CJ Leffe','-','-','-'],
['Asia','-','-','private','Clara Jinju Jeong','-','-','-'],
['Asia','-','-','private','Coco Feng','-','-','-'],
['Asia','-','-','private','Corinna Hi-Kyung Gehrke','-','-','-'],
['Asia','-','-','private','Cynthia Chen','-','-','-'],
['Asia','-','-','private','Daegu Tango Marathon','-','-','-'],
['Asia','-','-','private','Dahai Zhang','-','-','-'],
['Asia','-','-','private','Daisy Tsang','-','-','-'],
['Asia','-','-','private','Dalbong Dalbong','-','-','-'],
['Asia','-','-','private','Damian Desmaras','-','-','-'],
['Asia','-','-','private','Danielkim','-','-','-'],
['Asia','-','-','private','Darjeeling Yoonkyoung','-','-','-'],
['Asia','-','-','private','Dave Kim','-','-','-'],
['Asia','-','-','private','Diego Park','-','-','-'],
['Asia','-','-','private','Doheon Kwon','-','-','-'],
['Asia','-','-','private','Dongjin Lee','-','-','-'],
['Asia','-','-','private','Doya Doya Tango','-','-','-'],
['Asia','-','-','private','Duke Jun Lee','-','-','-'],
['Asia','-','-','private','Dust Wind','-','-','-'],
['Asia','-','-','private','Elisa Álvarez','-','-','-'],
['Asia','-','-','private','Elly Dong-eun Chung','-','-','-'],
['Asia','-','-','private','Elphie Cho','-','-','-'],
['Asia','-','-','private','Emma Jade','-','-','-'],
['Asia','-','-','private','Eric Zeng','-','-','-'],
['Asia','-','-','private','Erik Deslarmes','-','-','-'],
['Asia','-','-','private','Estelle Choi','-','-','-'],
['Asia','-','-','private','Eun Jung Cho','-','-','-'],
['Asia','-','-','private','Eun Mi Song','-','-','-'],
['Asia','-','-','private','Eunjeong An','-','-','-'],
['Asia','-','-','private','EunJi Sung','-','-','-'],
['Asia','-','-','private','Ezraa Jin','-','-','-'],
['Asia','-','-','private','Federico Kim','-','-','-'],
['Asia','-','-','private','Felicity Fung','-','-','-'],
['Asia','-','-','private','Felix Taehoon Kim','-','-','-'],
['Asia','-','-','private','Fiesta Collégĭum','-','-','-'],
['Asia','-','-','private','Flora Hanh Du','-','-','-'],
['Asia','-','-','private','Forest Vu','-','-','-'],
['Asia','-','-','private','Fuping Lee','-','-','-'],
['Asia','-','-','private','Gavi Ji-hye','-','-','-'],
['Asia','-','-','private','Gio Tomba','-','-','-'],
['Asia','-','-','private','Gordon Hui','-','-','-'],
['Asia','-','-','private','HA NI','-','-','-'],
['Asia','-','-','private','Hai Lee','-','-','-'],
['Asia','-','-','private','Han Pa','-','-','-'],
['Asia','-','-','private','Happyday Clara','-','-','-'],
['Asia','-','-','private','Hardy Ryu','-','-','-'],
['Asia','-','-','private','HARU','-','-','-'],
['Asia','-','-','private','Helen Guang','-','-','-'],
['Asia','-','-','private','Helen Wong','-','-','-'],
['Asia','-','-','private','Henzel Tango','-','-','-'],
['Asia','-','-','private','Holly Jang','-','-','-'],
['Asia','-','-','private','hug','-','-','-'],
['Asia','-','-','private','humberto','-','-','-'],
['Asia','-','-','private','Hwajin Isabella Lee','-','-','-'],
['Asia','-','-','private','Hwang Marquito Sung-uk','-','-','-'],
['Asia','-','-','private','Hwanjo Lim','-','-','-'],
['Asia','-','-','private','Hyang Gi Seo','-','-','-'],
['Asia','-','-','private','Hyejeong Park','-','-','-'],
['Asia','-','-','private','Hyeog-soo Ko','-','-','-'],
['Asia','-','-','private','Hygge Jung','-','-','-'],
['Asia','-','-','private','Hyoni JH','-','-','-'],
['Asia','-','-','private','HyunWook Jun','-','-','-'],
['Asia','-','-','private','I-fan Wu','-','-','-'],
['Asia','-','-','private','Ines Do','-','-','-'],
['Asia','-','-','private','Inkyoung Jang Siwa','-','-','-'],
['Asia','-','-','private','Irene Fong','-','-','-'],
['Asia','-','-','private','Irene Zhang','-','-','-'],
['Asia','-','-','private','Isaac Ho','-','-','-'],
['Asia','-','-','private','Jaesoo Lee','-','-','-'],
['Asia','-','-','private','Jane Lee','-','-','-'],
['Asia','-','-','private','Jay Hw','-','-','-'],
['Asia','-','-','private','Jee Yeon Yang','-','-','-'],
['Asia','-','-','private','Jennifer Campos','-','-','-'],
['Asia','-','-','private','Jenny Lo','-','-','-'],
['Asia','-','-','private','Jeong Wanhee Torr','-','-','-'],
['Asia','-','-','private','Jerald KIM','-','-','-'],
['Asia','-','-','private','Jezebel Dang','-','-','-'],
['Asia','-','-','private','Jin SU Song','-','-','-'],
['Asia','-','-','private','Jino Park Joon Gyun','-','-','-'],
['Asia','-','-','private','Joe Wu','-','-','-'],
['Asia','-','-','private','Jong Young Kim','-','-','-'],
['Asia','-','-','private','JS Choi','-','-','-'],
['Asia','-','-','private','Juan Jiwon Kim','-','-','-'],
['Asia','-','-','private','Jung A Jung','-','-','-'],
['Asia','-','-','private','Jungyi Yoon','-','-','-'],
['Asia','-','-','private','Kaan Tango','-','-','-'],
['Asia','-','-','private','Kai-Mai Aja','-','-','-'],
['Asia','-','-','private','Katarina Galabova','-','-','-'],
['Asia','-','-','private','Kelly Hwang','-','-','-'],
['Asia','-','-','private','Kevin Wang','-','-','-'],
['Asia','-','-','private','Kevin Yap','-','-','-'],
['Asia','-','-','private','KiHoon Park','-','-','-'],
['Asia','-','-','private','Kiki Jiyeon Lee','-','-','-'],
['Asia','-','-','private','Kim Wonkyoung','-','-','-'],
['Asia','-','-','private','KIMHYUNG GUN','-','-','-'],
['Asia','-','-','private','Kirmy Zhang','-','-','-'],
['Asia','-','-','private','Klaudia Ealing','-','-','-'],
['Asia','-','-','private','Kristof Elst','-','-','-'],
['Asia','-','-','private','Kwang Il Ko (Cheek To Cheek Flow)','-','-','https://www.facebook.com/CheekToCheekFlow'],
['Asia','-','-','private','Kwang Seob Kim','-','-','-'],
['Asia','-','-','private','Kyoko Tzu-Han','-','-','-'],
['Asia','-','-','private','Kyungsu Kim','-','-','-'],
['Asia','-','-','private','Labios Lee','-','-','-'],
['Asia','-','-','private','Lars Jung','-','-','-'],
['Asia','-','-','private','Laura Paun','-','-','-'],
['Asia','-','-','private','Lea Clio Han','-','-','-'],
['Asia','-','-','private','Lena Yoo','-','-','-'],
['Asia','-','-','private','Leon Junseok Lee','-','-','-'],
['Asia','-','-','private','Leonel Hung-Yut Chen','-','-','-'],
['Asia','-','-','private','Li Tzu Ling','-','-','-'],
['Asia','-','-','private','Lily Wang','-','-','-'],
['Asia','-','-','private','Liming Jiang','-','-','-'],
['Asia','Taiwan','Taipei','private','Lin Yuhsuan','marathon','KNOW','https://www.facebook.com/groups/1494663620822173/user/1321470056/'],
['Asia','-','-','private','Ling Huang','-','-','-'],
['Asia','-','-','private','Liu Zheng','-','-','-'],
['Asia','-','-','private','Love Won','-','-','-'],
['Asia','-','-','private','Luna Kim','-','-','-'],
['Asia','-','-','private','Maggie Zhang','-','-','-'],
['Asia','-','-','private','Mambo Mucho','-','-','-'],
['Asia','-','-','private','Mango Park','-','-','-'],
['Asia','-','-','private','Mano','-','-','-'],
['Asia','-','-','private','Manuel Manuel Ortiz','-','-','-'],
['Asia','-','-','private','Marco Kang','-','-','-'],
['Asia','-','-','private','Maria Kim','-','-','-'],
['Asia','-','-','private','Mariano Vázquez','-','-','-'],
['Asia','-','-','private','Mauge Corna','-','-','-'],
['Asia','-','-','private','May Kim','-','-','-'],
['Asia','-','-','private','Mi Soup Kim','-','-','-'],
['Asia','-','-','private','Mia Nguyen','-','-','-'],
['Asia','-','-','private','Miguel Calvo','-','-','-'],
['Asia','-','-','private','Milonga Orange','-','-','-'],
['Asia','-','-','private','Miran Lee','-','-','-'],
['Asia','-','-','private','Miri Murano','-','-','-'],
['Asia','-','-','private','MJ Kim','-','-','-'],
['Asia','-','-','private','Moses Park','-','-','-'],
['Asia','-','-','private','Muriel Kim','-','-','-'],
['Asia','-','-','private','Myeong A Ryu','-','-','-'],
['Asia','-','-','private','Myra Liu','-','-','-'],
['Asia','-','-','private','Nadia','-','-','-'],
['Asia','-','-','private','Natali Pak','-','-','-'],
['Asia','-','-','private','Neip Seon','-','-','-'],
['Asia','-','-','private','Neus Suarez','-','-','-'],
['Asia','-','-','private','Nhung Doan','-','-','-'],
['Asia','-','-','private','Nova Saver','-','-','-'],
['Asia','-','-','private','Nuncia Sisco Hernandez','-','-','-'],
['Asia','-','-','private','Odysseus Dada','-','-','-'],
['Asia','-','-','private','OJ Jo','-','-','-'],
['Asia','-','-','private','Okiz Okki Baek','-','-','-'],
['Asia','-','-','private','Oko Tango','-','-','-'],
['Asia','-','-','private','Olive Kim','-','-','-'],
['Asia','-','-','private','Orly Ha','-','-','-'],
['Asia','-','-','private','Palina Chan','-','-','-'],
['Asia','-','-','private','Park Euan','-','-','-'],
['Asia','-','-','private','Peidong Liu','-','-','-'],
['Asia','-','-','private','Perni Peng','-','-','-'],
['Asia','-','-','private','Pichard Lee','-','-','-'],
['Asia','-','-','private','Pu Ma ','-','-','https://www.facebook.com/pu.ma.732545/'],
['Asia','-','-','private','Qin Chen','-','-','-'],
['Asia','-','-','private','Qing Tang','-','-','-'],
['Asia','-','-','private','Qiuqiu Chen','-','-','-'],
['Asia','-','-','private','Rafael Busch','-','-','-'],
['Asia','-','-','private','Ray Li','-','-','-'],
['Asia','-','-','private','Rebecca Meow','-','-','-'],
['Asia','-','-','private','Rhona Yeajin Seo','-','-','-'],
['Asia','-','-','private','Rina Jung','-','-','-'],
['Asia','-','-','private','Rina Kang','-','-','-'],
['Asia','-','-','private','Rina Sawaya','-','-','-'],
['Asia','-','-','private','Rio Gao','-','-','-'],
['Asia','-','-','private','Rob Roy','-','-','-'],
['Asia','-','-','private','Rose Tai','-','-','-'],
['Asia','-','-','private','Rosie Gangmi Ji','-','-','-'],
['Asia','-','-','private','Ruróni Kami','-','-','-'],
['Asia','-','-','private','Ryan Gonz','-','-','-'],
['Asia','-','-','private','Ryan Hoang','-','-','-'],
['Asia','-','-','private','Ryuga-jin Kim','-','-','-'],
['Asia','-','-','private','Sabrina Chia','-','-','-'],
['Asia','-','-','private','Saku Tango','-','-','-'],
['Asia','-','-','private','Sang Yeon Woo','-','-','-'],
['Asia','-','-','private','Sarah Archala Ann Watt','-','-','-'],
['Asia','-','-','private','Sarah J Tango','-','-','-'],
['Asia','-','-','private','SARAH','-','-','-'],
['Asia','-','-','private','Scent HongYounghyo','-','-','-'],
['Asia','-','-','private','Sehoon Atom Son','-','-','-'],
['Asia','-','-','private','Seok June','-','-','-'],
['Asia','-','-','private','Shiao Chang','-','-','-'],
['Asia','-','-','private','Shim Changsoo','-','-','-'],
['Asia','-','-','private','Shuting Zhang','-','-','-'],
['Asia','-','-','private','Simjang Corazon Choi','-','-','-'],
['Asia','-','-','private','Simon Shin','-','-','-'],
['Asia','-','-','private','Siro Ki Ryeon Kim','-','-','-'],
['Asia','-','-','private','Sisi Wang','-','-','-'],
['Asia','-','-','private','Sofía Saborido','-','-','-'],
['Asia','-','-','private','Sol Seojeong Choi','-','-','-'],
['Asia','-','-','private','Solra Heo','-','-','-'],
['Asia','-','-','private','SongYan Li','-','-','-'],
['Asia','-','-','private','Soonhyun Kang','-','-','-'],
['Asia','-','-','private','Soyoung Park','-','-','-'],
['Asia','-','-','private','Ssun Sunjung','-','-','-'],
['Asia','-','-','private','Stacey Kim','-','-','-'],
['Asia','-','-','private','Stacy Jou','-','-','-'],
['Asia','-','-','private','Stefano Lee','-','-','-'],
['Asia','-','-','private','Stephen Liao','-','-','-'],
['Asia','-','-','private','Sugar Sumi','-','-','-'],
['Asia','-','-','private','Sungwoo Dulce Lee','-','-','-'],
['Asia','-','-','private','Sunjoo Lee','-','-','-'],
['Asia','-','-','private','Sunny Lee','-','-','-'],
['Asia','-','-','private','Sunshine','-','-','-'],
['Asia','-','-','private','Ta Tango','-','-','-'],
['Asia','-','-','private','Taeseon Lickey Iron Kim','-','-','-'],
['Asia','-','-','private','Taeyang Kim','-','-','-'],
['Asia','-','-','private','Tango Andante','-','-','-'],
['Asia','-','-','private','Tango Hanoi','-','-','-'],
['Asia','-','-','private','Tango Jin Epitone','-','-','-'],
['Asia','-','-','private','Tango Lily','-','-','-'],
['Asia','-','-','private','Tango Martini','-','-','-'],
['Asia','-','-','private','Tango Salida de Sol','-','-','-'],
['Asia','-','-','private','TangoJenny Qingdao','-','-','-'],
['Asia','-','-','private','Tanguera Riaa','-','-','-'],
['Asia','-','-','private','Tara Lee','-','-','-'],
['Asia','-','-','private','Teo Rumi Tango','-','-','-'],
['Asia','-','-','private','Terry Kang','-','-','-'],
['Asia','-','-','private','Thomas Cito','-','-','-'],
['Asia','-','-','private','Tomo Hoshino','-','-','-'],
['Asia','-','-','private','Tomoko Son','-','-','-'],
['Asia','-','-','private','Tony Royal','-','-','-'],
['Asia','-','-','private','Travelers Tango','-','-','-'],
['Asia','-','-','private','Ursula Pardo','-','-','-'],
['Asia','-','-','private','Veena Lee','-','-','-'],
['Asia','-','-','private','Vicky Nawon Kang','-','-','-'],
['Asia','-','-','private','Vivian Chen','-','-','-'],
['Asia','-','-','private','Vivian Si-eun Yoon','-','-','-'],
['Asia','-','-','private','Wanda Bunnylee','-','-','-'],
['Asia','-','-','private','Warren Chin','-','-','-'],
['Asia','-','-','private','Weiyi Yang','-','-','-'],
['Asia','-','-','private','Wood Wood','-','-','-'],
['Asia','-','-','private','Woori Serena','-','-','-'],
['Asia','-','-','private','Woorung Kim','-','-','-'],
['Asia','-','-','private','Xiaoi Tan','-','-','-'],
['Asia','-','-','private','Yavor Hsu','-','-','-'],
['Asia','-','-','private','YeJi Yoo','-','-','-'],
['Asia','-','-','private','YeonJoo Tango','-','-','-'],
['Asia','-','-','private','YeoYeon Choi','-','-','-'],
['Asia','-','-','private','Yi Qiao','-','-','-'],
['Asia','-','-','private','Yi Qing LI','-','-','-'],
['Asia','-','-','private','Yoonchan Kim','-','-','-'],
['Asia','-','-','private','Yoonkang Choi','-','-','-'],
['Asia','-','-','private','YoonKyung Hong','-','-','-'],
['Asia','-','-','private','Yoshinobu Gyu Nagai','-','-','-'],
['Asia','-','-','private','You Hyun Sung','-','-','-'],
['Asia','-','-','private','Yukari Matsuoka','-','-','-'],
['Asia','-','-','private','Yulia Kudelia','-','-','-'],
['Asia','-','-','private','Yuling Chen','-','-','-'],
['Asia','-','-','private','Yuriel Jung Ji Yun','-','-','-'],
['Asia','-','-','private','Yushan Pan','-','-','-'],
['Asia','-','-','private','Yutan Lin','-','-','-'],
['Asia','-','-','private','Yw Park','-','-','-'],
['Asia','-','-','private','Ze Ze','-','-','-'],
['Asia','-','-','private','Zhenyu Zhou','-','-','-'],
['Asia','-','-','private','Đante Joe Trắng','-','-','-'],
['Asia','-','-','private','김선미','-','-','-'],
['Asia','-','-','private','김은희','-','-','-'],
['Asia','-','-','private','김정환','-','-','-'],
['Asia','-','-','private','김한비','-','-','-'],
['Asia','-','-','private','김형주','-','-','-'],
['Asia','-','-','private','박정미 (grace mia)','-','-','-'],
['Asia','-','-','private','별장군','-','-','-'],
['Asia','-','-','private','비도','-','-','-'],
['Asia','-','-','private','이영미','-','-','-'],
['Asia','-','-','private','줄리엣','-','-','-'],
['Asia','-','-','private','지노유니','-','-','-'],
['Asia','Korea','Daejeon','private','하난숙','namuk','GOOD0,KNOW0','-'],
['Asia','-','-','private','Maggie Ho','-','-','https://www.facebook.com/maggie.ho.7927'],
['Asia','-','Seoul','private','Kim Seung Gi Giro','-','-','https://www.facebook.com/kim.seung.gi.giro'],
['Asia','-','Seoul','private','Nacho Jung Sehyung (정세형)','-','-','https://www.facebook.com/nacho.jungsehyung'],
['Asia','-','Seoul','private','Uno Byungwan Kim ','-','-','https://www.facebook.com/willbyungwan.kim'],
['Asia','-','Shanghai','private','Xiao Xin (LuCho)','-','-','https://www.facebook.com/xiao.xin.141301'],
['Asia','-','Shanghai','private','Lillian Cao','-','-','https://www.facebook.com/MsChaolillian'],
['Asia','Australia','-','private','Rui Rodrigues','-','-','-'],
['Asia','China','-','private','周立國','-','-','-'],
['Asia','China','-','private','孙越','-','-','-'],
['Asia','China','-','private','戴予軒','-','-','-'],
['Asia','China','-','private','潘倩倩 (Chann Pan)','-','-','https://www.facebook.com/pan.qian.qian.840148/'],
['Asia','China','-','private','簡寵時','-','-','-'],
['Asia','China','-','private','邢洪志','-','-','-'],
['Asia','China','-','private','Sissy Simonet','-','-','https://www.facebook.com/myraliu61'],
['Asia','China','Beijing','private','Elena Guo','-','-','https://www.facebook.com/yao.guo.94'],
['Asia','China','Beijing','private','李笑羚 ','-','KNOW2','https://www.facebook.com/li.xiao.ling.128237'],
['Asia','China','Beijing','private','Katerina Liu','-','-','https://www.facebook.com/profile.php?id=100086440194508&sk=about'],
['Asia','China','Beijing','private','Sarah Liu','-','-','https://www.facebook.com/sarah.liu.5477'],
['Asia','China','Beijing','private','Yingzhu Chen','-','-','https://www.facebook.com/yingzhu.chen.334/about'],
['Asia','China','Chengdu','private','Panda LU (Panda and Lucia)','-','-','https://www.facebook.com/profile.php?id=61551933811748&sk='],
['Asia','China','Chengdu','private','Joyce Chen','-','-','https://www.facebook.com/joyce.chen.842599/'],
['Asia','China','Gwangju','private','余思彧','-','-','https://www.facebook.com/hotysy'],
['Asia','China','Hangzhou','private','Yuting Dong (dd)','-','-','https://www.facebook.com/profile.php?id=100093581882493&sk='],
['Asia','China','Henzhen','private','Aykut Kazanci','Luna Tango, Henzhen Tango Maraencuentro','-','https://www.facebook.com/aykut.kazanci/about'],
['Asia','China','Hong Kong','private','Angel Yu','-','-','https://www.facebook.com/angel.yu.1884/'],
['Asia','China','Hong Kong','private','Ivy Tulip','-','-','https://www.facebook.com/ivytulip/about'],
['Asia','China','Hong Kong','private','Rosanne Li','-','-','https://www.facebook.com/rosanneli'],
['Asia','China','Qingdao','private','Vivian Li','-','-','https://www.facebook.com/profile.php?id=100091371874021&sk=about'],
['Asia','China','Shanghai','private','Kai Wang','te amo tango lounge','(from Taipei)','-'],
['Asia','China','Shanghai','private','Weiwei QI','regina shoes','-','https://www.facebook.com/weiwei.qi.92'],
['Asia','China','Shanghai','private','Aoyu Fan','-','-','https://www.facebook.com/aoyu.fan.2025/'],
['Asia','China','Shanghai','private','Benton Wang','-','-','https://www.facebook.com/benton3301'],
['Asia','China','Shanghai','private','Diane Zhang','-','-','https://www.facebook.com/diane.zhang.737/'],
['Asia','China','Shanghai','private','Elena Zhang','-','-','https://www.facebook.com/profile.php?id=61560642938564&sk='],
['Asia','China','Shanghai','private','Sergiy Podbolotnyy','-','-','https://www.facebook.com/sergiy.podbolotnyy/'],
['Asia','China','Shanghai','private','Desiree Hong','-','-','https://www.facebook.com/profile.php?id=61557893514467'],
['Asia','China','Shanghai','private','Joanna Zheng','-','-','https://www.facebook.com/joanna.zheng.142'],
['Asia','China','Shanghai','private','Stella Guo','-','-','https://www.facebook.com/stella.guo.737069'],
['Asia','China','Shenzhen','private','Jo Xia ',',vive en Marsella,me asiva de sus eventos','KNOW2','https://www.facebook.com/jojoxia33'],
['Asia','Hong Kong','Hong Kong','private','Jacky Ma','Imperial Society of Teachers of Dancing','-','https://www.facebook.com/lungjacky/'],
['Asia','Japan','Akishima','private','Aki Tanaka','-','-','https://www.facebook.com/aki.tanaka.1213986'],
['Asia','Japan','Kyoto','private','Kimiko Lena Osaka','-','KNOW','https://www.facebook.com/kimiko.lena.osaka'],
['Asia','Japan','Tokyo','private','Kyoto Tango','-','-','-'],
['Asia','Japan','Tokyo','private','Kyoko Stuhlmann','-','KNOW','https://www.facebook.com/kyoko.stuhlmann'],
['Asia','Korea','-','private','Alex Jonghwa Tangodj','-','-','-'],
['Asia','Korea','-','private','Howoon Chung (El Loco)','-','-','-'],
['Asia','Korea','-','private','Sangdam Sojang Kim (상담소장)','-','-','https://www.facebook.com/sangdamsojang'],
['Asia','Korea','-','private','IF Kim','-','-','-'],
['Asia','Korea','-','private','Jihyun Lee (Dalsarli)','-','-','https://www.facebook.com/jihyun.lee.0731/about'],
['Asia','Korea','-','private','감자','-','-','-'],
['Asia','Korea','-','private','고희영','-','-','-'],
['Asia','Korea','-','private','김성우','-','-','-'],
['Asia','Korea','-','private','김송하','-','-','-'],
['Asia','Korea','-','private','김수지','-','-','-'],
['Asia','Korea','-','private','김우정','-','-','-'],
['Asia','Korea','-','private','김은진','-','-','-'],
['Asia','Korea','-','private','김인선','-','-','-'],
['Asia','Korea','-','private','김정아','-','-','-'],
['Asia','Korea','-','private','김지현 (냥이)','-','-','https://www.facebook.com/gimjihyeon.317355/'],
['Asia','Korea','-','private','대청마루','-','-','-'],
['Asia','Korea','-','private','로즈','-','-','-'],
['Asia','Korea','-','private','리수','-','-','-'],
['Asia','Korea','-','private','마선장','-','-','-'],
['Asia','Korea','-','private','멜로디언','-','-','-'],
['Asia','Korea','-','private','바람','-','-','-'],
['Asia','Korea','-','private','박성준','-','-','-'],
['Asia','Korea','-','private','박수승','-','-','-'],
['Asia','Korea','-','private','박용준','-','-','-'],
['Asia','Korea','-','private','박중리','-','-','-'],
['Asia','Korea','-','private','박하비','-','-','-'],
['Asia','Korea','-','private','배성곤','-','-','-'],
['Asia','Korea','-','private','부현철','-','-','-'],
['Asia','Korea','-','private','비비','-','-','-'],
['Asia','Korea','-','private','서성우 (다 옹)','-','-','https://www.facebook.com/seoseong.u.779721'],
['Asia','Korea','-','private','서정민','-','-','-'],
['Asia','Korea','-','private','손경호','-','-','-'],
['Asia','Korea','-','private','시노','-','-','-'],
['Asia','Korea','-','private','심서영','-','-','-'],
['Asia','Korea','-','private','아사','-','-','-'],
['Asia','Korea','-','private','안철휘','-','-','-'],
['Asia','Korea','-','private','에릭','-','-','-'],
['Asia','Korea','-','private','에비타','-','-','-'],
['Asia','Korea','-','private','오즈','-','-','-'],
['Asia','Korea','-','private','우승철','-','-','-'],
['Asia','Korea','-','private','울라','-','-','-'],
['Asia','Korea','-','private','위드','-','-','-'],
['Asia','Korea','-','private','유명희','-','-','-'],
['Asia','Korea','-','private','이베트','-','-','-'],
['Asia','Korea','-','private','이용화','-','-','-'],
['Asia','Korea','-','private','이진아','-','-','-'],
['Asia','Korea','-','private','임강현','-','-','-'],
['Asia','Korea','-','private','전경식','-','-','-'],
['Asia','Korea','-','private','정순태','-','-','-'],
['Asia','Korea','-','private','정연근','-','-','-'],
['Asia','Korea','-','private','정용이','-','-','-'],
['Asia','Korea','-','private','조민규','-','-','-'],
['Asia','Korea','-','private','죠죠','-','-','-'],
['Asia','Korea','-','private','채송화','-','-','-'],
['Asia','Korea','-','private','최규웅','-','-','-'],
['Asia','Korea','-','private','최미선','-','-','-'],
['Asia','Korea','-','private','최성식','-','-','-'],
['Asia','Korea','-','private','최현호','-','-','-'],
['Asia','Korea','-','private','크루','-','-','-'],
['Asia','Korea','-','private','피비','-','-','-'],
['Asia','Korea','-','private','하나비','-','-','-'],
['Asia','Korea','-','private','한걸음','-','-','-'],
['Asia','Korea','-','private','한지아','-','-','-'],
['Asia','Korea','-','private','함철환','-','-','-'],
['Asia','Korea','-','private','헤이지','-','-','-'],
['Asia','Korea','-','private','Cya Lu','-','-','-'],
['Asia','Korea','-','private','이선의 (보카)','-','-','https://www.facebook.com/profile.php?id=100009318804955&sk='],
['Asia','Korea','-','private','Isa Dora','-','KNOW,GOOD','-'],
['Asia','Korea','-','private','KKao Isk (까오)','-','-','https://www.facebook.com/kkao.isk/'],
['Asia','Korea','Anyang','private','남은주 (이제이)','-','-','https://www.facebook.com/nam.eunju.188189/'],
['Asia','Korea','Busan','private','Gonny Jigon Park','Tango WK El Mar','-','https://www.facebook.com/jigon.park.739'],
['Asia','Korea','Busan','private','Kang Seong Jin Ivan','-','-','https://www.facebook.com/seongjin.kang'],
['Asia','Korea','Busan','private','Exo Jang (장진현)','-','-','https://www.facebook.com/jang.jinhyeon/'],
['Asia','Korea','Busan','private','일락','-','-','https://www.facebook.com/illag.479850/'],
['Asia','Korea','Busan','private','Kimi Seung Joo Kim ','-','-','https://www.facebook.com/kimiseungjoo.kim/about'],
['Asia','Korea','Busan','private','Shawn Sung Yeal Kwon','-','-','-'],
['Asia','Korea','Busan','private','초아','-','-','https://www.facebook.com/yunkyung.cho.39'],
['Asia','Korea','Changwon','private','박경난 (Nan-a)','-','-','https://www.facebook.com/nan041004/'],
['Asia','Korea','Changwon','private','Anna Choi','-','-','https://www.facebook.com/anna.choi.794009/'],
['Asia','Korea','Cheonan','private','Kyoungsik Ha (Hagoon)','-','-','https://www.facebook.com/kyoungsik.ha/about'],
['Asia','Korea','Cheongju','private','Sofia Yeoreum','Studio Aura','-','https://www.facebook.com/sofia.yeoreum/'],
['Asia','Korea','Chuncheon','private','이나래 (Narae)','-','-','https://www.facebook.com/tango.narae/'],
['Asia','Korea','Daegu','private','Nabi Nabi','-','-','https://www.facebook.com/nabi.nabi.397220'],
['Asia','Korea','Daegu','private','Do Hwangbo (Dylan)','-','-','https://www.facebook.com/do.hwangbo.5/'],
['Asia','Korea','Daejeon','private','Diego Ki','-','-','-'],
['Asia','Korea','Daejeon','private','Sejin Jeong','-','-','https://www.facebook.com/sejin.jeong.7334/'],
['Asia','Korea','Daejeon','private','최철호 (벨제붑)','-','-','https://www.facebook.com/kiki4985/'],
['Asia','Korea','Daejeon','private','Darby Yang (Wony)','-','-','https://www.facebook.com/wony.yang.12/about'],
['Asia','Korea','Incheon','private','Dopamine Henry','-','-','https://www.facebook.com/henry.wotton.357/'],
['Asia','Korea','Jinju','private','Eun Ju Lee','-','-','https://www.facebook.com/eun.ju.lee.835975'],
['Asia','Korea','Pohang','private','신비 (신비)','-','-','https://www.facebook.com/sinbi.953278/about'],
['Asia','Korea','Seongnam','private','Zavo Yurius','-','-','https://www.facebook.com/tangovuelo/'],
['Asia','Korea','Seongnam','private','Mario Kim ','-','-','https://www.facebook.com/mario.kim.821506/about'],
['Asia','Korea','Seoul','private','Aran Sunmi Kang','En Paz','-','https://www.facebook.com/aran.sunmikang/photos'],
['Asia','Korea','Seoul','private','Beto Kim','-','-','https://www.facebook.com/byeoungjun.kim.9'],
['Asia','Korea','Seoul','private','Eugene Bien','-','-','-'],
['Asia','Korea','Seoul','private','GaEa Kim','organizer','-','-'],
['Asia','Korea','Seoul','private','Gianluca Seo','-','-','https://www.facebook.com/gianluca.seo/'],
['Asia','Korea','Seoul','private','Hyo-jung Oh','-','-','-'],
['Asia','Korea','Seoul','private','Kogsan Kyuho Kim','TangoLife','-','https://www.facebook.com/kogsan.kyuho.kim'],
['Asia','Korea','Seoul','private','Sophia Chung','Milonga Bulgeum - Onada','-','-'],
['Asia','Korea','Seoul','private','Youngsun Lee','Gusan Sunset Tango Maraton','-','https://www.facebook.com/youngsun.lee/about'],
['Asia','Korea','Seoul','private','Christy Kim','-','-','-'],
['Asia','Korea','Seoul','private','El Torito JiWoon Park','-','-','https://www.facebook.com/jiwoon.park.165/about'],
['Asia','Korea','Seoul','private','Hyung Jun Kim','-','-','https://www.facebook.com/dearmrkim/'],
['Asia','Korea','Seoul','private','Jeon Ejae Rio','-','-','https://www.facebook.com/rio.su.hyun.jeon/'],
['Asia','Korea','Seoul','private','Lilian S Seo','-','-','https://www.facebook.com/sungsook.seo.5/'],
['Asia','Korea','Seoul','private','Miae Tracy Kim (Tracy)','탱고달트랑 Tango DalTrang','-','https://www.facebook.com/tracymiaekim/'],
['Asia','Korea','Seoul','private','Seethrough Anese Kim','-','-','https://www.facebook.com/anese.kim/'],
['Asia','Korea','Seoul','private','Seon Min Lee (포포)','-','-','https://www.facebook.com/sunmin.lee.372'],
['Asia','Korea','Seoul','private','Woody Park','-','-','https://www.facebook.com/woody.park.2025/'],
['Asia','Korea','Seoul','private','강지우','-','-','https://www.facebook.com/gangjiu.630493/'],
['Asia','Korea','Seoul','private','김영우 (Hernan)','-','-','https://www.facebook.com/gim.yeong.u.498835/'],
['Asia','Korea','Seoul','private','Geff Kim Taehwan','-','-','-'],
['Asia','Korea','Seoul','private','Hyun Jung Kim','Luminoso','-','https://www.facebook.com/luminoso.trees'],
['Asia','Korea','Seoul','private','Eely','-','KNOW2','https://www.facebook.com/Illee17/about'],
['Asia','Korea','Seoul','private','Arbol Park','-','-','https://www.facebook.com/pilpreg/about'],
['Asia','Korea','Seoul','private','Aritta Angel','-','-','https://www.facebook.com/ArittaDongwooKim/about'],
['Asia','Korea','Seoul','private','Cheen Dancer (Mellow-Deep)','-','-','https://www.facebook.com/kyungcheen/about'],
['Asia','Korea','Seoul','private','Elvira Wang','-','-','https://www.facebook.com/profile.php?id=61560505666164&sk=about'],
['Asia','Korea','Seoul','private','Han-a Park','-','KNOW,GOOD','-'],
['Asia','Korea','Seoul','private','Heeyeon Chang','-','-','https://www.facebook.com/heeyeon.jang.37'],
['Asia','Korea','Seoul','private','Ku Young Joo (gloria)','-','-','https://www.facebook.com/ku.young.joo/about'],
['Asia','Korea','Seoul','private','Park Ursula ','-','-','https://www.facebook.com/park.ursula/about'],
['Asia','Korea','Seoul','private','Sharon Hakrim Son','-','-','https://www.facebook.com/sharonshoes'],
['Asia','Korea','Seoul','private','StellaKang','-','-','https://www.facebook.com/stellakang.2024/about'],
['Asia','Korea','Seoul','private','Ds Kim','-','-','https://www.facebook.com/VailamosJay/'],
['Asia','Korea','Seoul','private','Libe Tango ','-','-','https://www.facebook.com/libe.tango.2025/about'],
['Asia','Korea','Seoul','private','Victor Cho Hojong (victor cho)','-','-','https://www.facebook.com/victor.cho.hojong/about'],
['Asia','Korea','Suncheon','private','오승준 (bongbong)','-','-','https://www.facebook.com/profile.php?id=100002148016502'],
['Asia','Korea','Suwon','private','Sungjong Lee','-','-','https://www.facebook.com/sungjong.lee.58367116/about'],
['Asia','Korea','Yangpyeong','private','Isabelle (이사벨)','-','-','https://www.facebook.com/lsabelle.1004/'],
['Asia','Korea','Yongin','private','Lavan Kizomba','-','-','-'],
['Asia','Malaysia','Penang','private','Lynda Goh Lay Chin','-','-','https://www.facebook.com/laychin.goh/'],
['Asia','New Zeland','-','private','Nina Bailarina','-','KNOW','-'],
['Asia','Phillipines','Vigan','private','Erwin Sotelo Urbien','-','-','https://www.facebook.com/erwin.s.urbien/about'],
['Asia','Shanghai','China','private','Elaine Gu ','-','-','https://www.facebook.com/yi.gu.7140'],
['Asia','Singapore','Singapore','private','Andrienne Tho','Singapore Tango Marathon','-','https://www.facebook.com/andrienne.tho/'],
['Asia','Singapore','Singapore','private','Carman Chung','-','-','-'],
['Asia','Singapore','Singapore','private','Kat Leong','-','-','-'],
['Asia','Taiwan','-','private','Grace Liman Chan','-','-','-'],
['Asia','Taiwan','-','private','Claire Chang','-','KNOW','-'],
['Asia','Taiwan','Taipei','private','Lucrecia','la conoci en una practica,ferrari','KNOW,GOOD','https://www.facebook.com/yichun.huang.902'],
['Asia','Taiwan','Taipei','private','Satine Chiang','-','KNOW,GOOD0','https://www.facebook.com/satine.chiang.5'],
['Asia','Taiwan','Taipei','private','Chanbee Bokchan Park','Tango Busan Weekend','-','https://www.facebook.com/bokchan.park'],
['Asia','Taiwan','Taipei','private','Sheen Chan','-','-','https://www.facebook.com/lovesheen'],
['Asia','Taiwan','Taipei','private','陳東杰 (Tung-Chien Chen)','-','-','https://www.facebook.com/djchen0914/about'],
['Asia','Taiwan','Taipei','private','Queenie Huang','-','KNOW','https://www.facebook.com/queenie.huang.257/about'],
['Asia','Taiwan','Taipei','private','Sarita Chen','-','-','https://www.facebook.com/harptaiwan/about'],
['Asia','Thailandia','Chiang Mai','private','Cara Lu','-','KNOW2','-'],
['Asia','Vietnam','Hanoi','private','Nguyen Phuong Ngoc (Moon Luna)','Luna Tango encuentro','-','https://www.facebook.com/ngocxiu2001'],
['Europe','Spain','Valencia','private','Ana B Martin','-','KNOW','-'],
['Europe','Spain','Guadalajara','private','Ana Sánchez-Herrera','-','KNOW','-'],
['Europe','-','-','private','Malena Christiane Maack','-','KNOW','-'],
['Europe','-','-','private','Marco Maretti Tango','-','-','-'],
['Europe','Italy','Naple','private','Pasquale Barbaro','-','KNOW','-'],
['Europe','Spain','Vitoria','private','Pilar Iñiguez de Ciriano','-','KNOW','-'],
['Europe','Spain','Sevilla','private','Rafa Chacón','-','KNOW','-'],
['Europe','-','-','private','Tanya Zenina','2025 tango noon berlin','KNOW','-'],
['Europe','-','-','private','Belén Naw','-','-','-'],
['Europe','-','-','private','Carme Carmela','-','-','-'],
['Europe','-','-','private','Tomasz Zabrzyjewski','-','KNOW','-'],
['Europe','Barcelona','-','private','Alexis Quezada','-','-','-'],
['Europe','Catalunya','Barcelona','private','Ciro Llueca','-','-','-'],
['Europe','Czechia','-','private','Ondřej Tango','marathon praga','KNOW','-'],
['Europe','France','-','private','Sarah Le Bret','-','KNOW','-'],
['Europe','France','-','private','Céline Garrabos','-','KNOW','-'],
['Europe','France','-','private','Fabien Roujean','-','-','-'],
['Europe','France','Bordeaux','private','Tatiana Roujean','-','KNOW','-'],
['Europe','France','Antibes','private','Yun Liu','-','KNOW2,KNOW','niza en su chalet from Yongzhou China'],
['Europe','France','Lyon','private','Diego Riemer','en casa de Yun Liu','KNOW','-'],
['Europe','France','Toulouse','private','Odemue Odemue','-','KNOW','-'],
['Europe','Germany','-','private','Roswitha Tango-Atlántico','-','KNOW','-'],
['Europe','Germany','-','private','Alma Mia','-','-','-'],
['Europe','Germany','-','private','Deborah Maus','-','KNOW','-'],
['Europe','Germany','Berlin','private','Coco Mi Hee Kim','-','-','-'],
['Europe','Germany','Munich','private','Sylvia Viñez','papusa','KNOW','-'],
['Europe','Holand','Rotterdam','private','Charlie Cool','-','-','https://www.facebook.com/charlie.cool.100'],
['Europe','Italy','Roma','private','Chiara Biagini','-','KNOW','-'],
['Europe','Italy','-','private','Ignacio Cavalieri','-','KNOW','-'],
['Europe','Italy','Calgari','private','Rita Rolando','-','KNOW','-'],
['Europe','Lithuania','Vilnius','private','Mažena Milutė ','-','-','-'],
['Europe','Lituania','Vilnius','private','Olga Makhno','-','-','https://www.facebook.com/olga.makhno.7/about'],
['Europe','Netherlands','Amsterdam','private','Marta Kossakowska','-','-','https://www.facebook.com/marta.kossakowska/'],
['Europe','Poland','-','private','Iwona Z Tango','-','KNOW','-'],
['Europe','Poland','Miedzyborow','private','Ernest Winkowski','el gordo','-','https://www.facebook.com/ernest.winkowski/about'],
['Europe','Portugal','Lisboa','private','Lydia Elisabeth','dejo de bailar','KNOW','-'],
['Europe','Spain','-','private','David Reus','-','KNOW','-'],
['Europe','Spain','-','private','Fernando Nahmijas','-','KNOW','-'],
['Europe','Spain','-','private','RoqueyGiselle Castellano GaticaLujan','-','KNOW','-'],
['Europe','Spain','-','private','Adriana Herrera','-','-','-'],
['Europe','Spain','-','private','Enrique Ramírez','-','KNOW','-'],
['Europe','Spain','-','private','Francisca Ojeda','-','KNOW','-'],
['Europe','Spain','-','private','Guadalupe Lores','-','-','-'],
['Europe','Spain','-','private','Santiago Gala','-','KNOW','-'],
['Europe','Spain','-','private','Victoria Huang','-','-','-'],
['Europe','Spain','-','private','Elena Blanco Zala','-','-','-'],
['Europe','Spain','Barcelona','private','Maribel Bazán','-','KNOW','-'],
['Europe','Spain','Bilbao','private','BorjayChristina TangoBilbao','-','KNOW','-'],
['Europe','Spain','Bilbao','private','Marian Santin Manso','-','-','-'],
['Europe','Spain','Madrid','private','Claudio Fernando Cardona','-','KNOW','-'],
['Europe','Spain','Madrid','private','Maria Antonieta Tuozzo','-','KNOW','-'],
['Europe','Spain','Madrid','private','Maureen Lopez','-','KNOW','-'],
['Europe','Spain','Madrid','private','Raquel Domenech Fernandez','-','-','-'],
['Europe','Spain','Madrid','private','Gisele Góngora','-','KNOW','-'],
['Europe','Spain','Madrid','private','Carmen De La Rosa - Tango','-','KNOW','-'],
['Europe','Spain','Madrid','private','John Arbelaez','-','-','-'],
['Europe','Spain','Madrid','private','Jose Luis Soler Baillo','-','KNOW','-'],
['Europe','Spain','Madrid','private','Loic Vix','la melange','-','-'],
['Europe','Spain','Madrid','private','Sara Lorés Ara','-','-','-'],
['Europe','Spain','Madrid','private','Teresa Yoldi Salinas','-','KNOW','-'],
['Europe','Spain','Madrid','private','Marina Cendon','-','KNOW,TRAY','https://www.facebook.com/marina.cendon/'],
['Europe','Spain','Madrid','private','Rosa Monge','telegram','KNOW,TRAY','https://wHeeyeonww.facebook.com/rosa.monge'],
['Europe','Spain','Mallorca','private','Laura Macias Martinez','-','-','-'],
['Europe','Spain','San Sebastian','private','Amaia Tango','-','KNOW,TRAY','-'],
['Europe','Spain','Sevilla','private','Tango Petricor','-','-','-'],
['Europe','Spain','Sevilla','private','Gaston Godoy','-','-','-'],
['Europe','Spain','Sevilla','private','Maria Jose Chaves','-','-','-'],
['Europe','Spain','Sevilla','private','Alvaro Martinez','-','-','-'],
['Europe','Spain','Zaragoza','private','Coco Tango','-','-','-'],
['Europe','Sweden','-','private','Luis Cono','-','-','-'],
['Europe','Sweden','-','private','Muzi Ch','-','-','-'],
['Europe','Switzerland','-','private','Sia AliBaba','-','-','-'],
['-','-','-','private','Seon Min Lee','-','-','-'],
['-','-','-','private','Beau Chispita Kim','-','-','-'],
['-','-','-','private','Elaine Gu','-','-','-'],
['-','-','-','private','Yulia Yang','-','-','-'],
['-','-','-','private','潘倩倩','-','-','-'],
['Asia','Vietnam','Ho Chi Minh City','private','LyLy Dao','-','-','-'],
['-','-','-','private','Do Hwangbo','-','-','-'],
['-','-','-','private','Tanguero Iphty','-','-','-'],
['-','-','-','private','劉駿紳','-','-','-'],
['-','-','-','private','Matilda Seonga Ju','-','-','-'],
['-','-','-','private','Sarah Han','-','-','-'],
['-','-','-','private','Grace J','-','-','-'],
['-','-','-','private','Zingzing Lee','-','-','-'],
['-','-','-','private','Luca Zammitti','-','-','-'],
['-','-','-','private','Iri-arte Tangopeople','-','-','-'],
['-','-','-','private','Cemal Koran','-','-','-'],
['-','-','-','private','이나래','-','-','-'],
['-','-','-','private','SICHORE','-','-','-'],
['-','-','-','private','Nguyen Phuong Ngoc','-','-','-'],
['-','-','-','private','렉스','-','-','-'],
['-','-','-','private','Montaña Jose Luis','-','-','-'],
['-','-','-','private','Jessie Jiao','-','-','-'],
['-','-','-','private','La brisa','-','-','-'],
['-','-','-','private','Bruno Tango','-','-','-'],
['-','-','-','private','문영희','-','-','-'],
['-','-','-','private','陳瑾蓉','-','-','-'],
['-','-','-','private','Vera Chen','-','-','-'],
['-','-','-','private','Kyoungsik Ha','-','-','-'],
['-','-','-','private','탱고박미','-','-','-'],
['-','-','-','private','Shao Min','-','-','-'],
['-','-','-','private','Belinda Chan Lamyan','-','-','-'],
['-','-','-','private','Isabelle','-','-','-'],
['-','-','-','private','이선의','-','-','-'],
['-','-','-','private','李笑羚','-','-','-'],
['-','-','-','private','Barbie Jeon','-','-','-'],
['-','-','-','private','Kwang Il Ko','-','-','-'],
['-','-','-','private','J. Park','-','-','-'],
['-','-','-','private','Cynthia Fanta','-','-','-'],
['-','-','-','private','Sapphire Ho','-','-','-'],
['-','-','-','private','Teresa Ngo Lan Huong','-','-','-'],
['-','-','-','private','Aki Takahashi','-','-','-'],
['-','-','-','private','윤순미','-','-','-'],
['-','-','-','private','쟈벨','-','-','-'],
['-','-','-','private','함미순','-','-','-'],
['-','-','-','private','YONA','-','-','-'],
['-','-','-','private','Lavinia Livi','-','-','-'],
['-','-','-','private','Geumwon Jeon','-','-','-'],
['-','-','-','private','이영원','-','-','-'],
['-','-','-','private','Nacho Jung Sehyung','-','-','-'],
['-','-','-','private','김대우','-','-','-'],
['-','-','-','private','Guwoo Vicky','-','-','-'],
['-','-','-','private','Jihyun Lee','-','-','-'],
['-','-','-','private','Rom','-','-','-'],
['-','-','-','private','Sujin Lee','-','-','-'],
['-','-','-','private','Yvonne Jungmin Woo','-','-','-'],
['-','-','-','private','EVAN','-','-','-'],
['-','-','-','private','Francy Yang','-','-','-'],
['-','-','-','private','Chica Jieun Youm','-','-','-'],
['-','-','-','private','Mažena Milutė','-','-','-'],
['-','-','-','private','Yuting Dong','-','-','-'],
['-','-','-','private','May Su','-','-','-'],
['-','-','-','private','Ku Young Joo','-','-','-'],
['-','-','-','private','Steven Zhang','-','-','-'],
['-','-','-','private','Rena Crasiel','-','-','-'],
['-','-','-','private','yeoyeon choi .supia','-','-','-'],
['-','-','-','private','신비','-','-','-'],
['-','-','-','private','Chu-da','-','-','-'],
['-','-','-','private','풀초','-','-','-'],
['-','-','-','private','Eun Suk Jin','-','-','-'],
['-','-','-','private','Ken Lee','-','-','-'],
['-','-','-','private','Gyu Lee','-','-','-'],
['-','-','-','private','진아','-','-','-'],
['-','-','-','private','Woisuk Lee','-','-','-'],
['-','-','-','private','Wendy Yoon','-','-','-'],
['-','-','-','private','Elisha Hwt','-','-','-'],
['-','-','-','private','Lizi Sooyeon Lee','-','-','-'],
['-','-','-','private','Luna Dobin Moon','-','-','-'],
['-','-','-','private','Mario Kim','-','-','-'],
['-','-','-','private','Alva Kwong','-','-','-'],
['-','-','-','private','Dana Song','-','-','-'],
['-','-','-','private','Minh Trang','-','-','-'],
['-','-','-','private','Tango Vuelo','-','-','-'],
['-','-','-','private','Gimhae Tango Vuelta','-','-','-'],
['-','-','-','private','Miracle Ever','-','-','-'],
['-','-','-','private','Lucas Guo','-','-','-'],
['-','-','-','private','가희아','-','-','-'],
['-','-','-','private','Hao Chen','-','-','-'],
['-','-','-','private','박정미','-','-','-'],
['-','-','-','private','Alma Feliz Yachtie Kim','-','-','-'],
['-','-','-','private','Wei Wang','-','-','-'],
['-','-','-','private','Jihae Jung','-','-','-'],
['-','-','-','private','NowGood Tango Webtoon','-','-','-'],
['-','-','-','private','Teo Kwon DjHoon','-','-','-'],
['-','-','-','private','May Zhang','-','-','-'],
['-','-','-','private','Jinseon Oh','-','-','-'],
['-','-','-','private','Kimi Seung Joo Kim','-','-','-'],
['-','-','-','private','Shirley Hong','-','-','-'],
['-','-','-','private','Pu Ma','-','-','-'],
['-','-','-','private','민새','-','-','-'],
['-','-','-','private','Dalja Amable','-','-','-'],
['-','-','-','private','Yeonjeong An','-','-','-'],
['-','-','-','private','Nikita Chow','-','-','-'],
['-','-','-','private','Caminito Art','-','-','-'],
['-','-','-','private','서성우','-','-','-'],
['-','-','-','private','Jue Wang','-','-','-'],
['-','-','-','private','Noe Thuy','-','-','-'],
['-','-','-','private','Gasol He','-','-','-'],
['-','-','-','private','Sunny Cao','-','-','-'],
['-','-','-','private','Lubi Tango','-','-','-'],
['-','-','-','private','Ke Ke','-','-','-'],
['-','-','-','private','이용기','-','-','-'],
['-','-','-','private','Vino Yoon','-','-','-'],
['-','-','-','private','Mimi MC','-','-','-'],
['-','-','-','private','Bumwon Nam','-','-','-'],
['-','-','-','private','Manh Manh','-','-','-'],
['-','-','-','private','Flora Jeon','-','-','-'],
['-','-','-','private','Layla Jinhee Lee','-','-','-'],
['-','-','-','private','김세라','-','-','-'],
['-','-','-','private','Tango Liu Zhengzhong','-','-','-'],
['-','-','-','private','Roberto Wang','-','-','-'],
['-','-','-','private','김성준','-','-','-'],
['-','-','-','private','Macy Wu','-','-','-'],
['-','-','-','private','Ban A Lee','-','-','-'],
['-','-','-','private','김영우','-','-','-'],
['-','-','-','private','차성범','-','-','-'],
['-','-','-','private','Xiao Xin','-','-','-'],
['-','-','-','private','Justin Zhao','-','-','-'],
['-','-','-','private','Cityhallpics Sf','-','-','-'],
['-','-','-','private','Teddy Wong','-','-','-'],
['-','-','-','private','Diane Liu','-','-','-'],
['-','-','-','private','Zacky Abror','-','-','-'],
['-','-','-','private','Fujiko Sumiko Tanaka','-','-','-'],
['-','-','-','private','Libe Tango','-','-','-'],
['-','-','-','private','김지현','-','-','-'],
['-','-','-','private','Dreaming Park','-','-','-'],
['-','-','-','private','Daiana Guspero III','-','-','-'],
['-','-','-','private','Aeon Wang','-','-','-'],
['-','-','-','private','Hansoo Cho','-','-','-'],
['-','-','-','private','Caesar Lee','-','-','-'],
['-','-','-','private','노형준','-','-','-'],
['-','-','-','private','박성림','-','-','-'],
['-','-','-','private','이성재','-','-','-'],
['-','-','-','private','Maggie Suzuki','-','-','-'],
['-','-','-','private','Hyesun Lee','-','-','-'],
['-','-','-','private','제미최','-','-','-'],
['-','-','-','private','Jennie Valeria','-','-','-'],
['-','-','-','private','Patricia Bai','-','-','-'],
['-','-','-','private','Lucrecia YiChun Huang','-','-','-'],
['-','-','-','private','Jieun Song','-','-','-'],
['-','-','-','private','Billy Lee','-','-','-'],
['-','-','-','private','리사','-','-','-'],
['-','-','-','private','Mina Lee','-','-','-'],
['-','-','-','private','Hiroki Kato Keiko Fukuda','-','-','-'],
['-','-','-','private','남은주','-','-','-'],
['-','-','-','private','Park Ursula','-','-','-'],
['-','-','-','private','최두형','-','-','-'],
['-','-','-','private','Hyunjin Choi','-','-','-'],
['-','-','-','private','Eun Jae Lee','-','-','-'],
['-','-','-','private','Uno Byungwan Kim','-','-','-'],
['-','-','-','private','Haerim Jung','-','-','-'],
['-','-','-','private','Miroo Kim','-','-','-'],
['-','-','-','private','Ki Ean Nam','-','-','-'],
['-','-','-','private','Anibal Wang','-','-','-'],
['-','-','-','private','Akira Haruki','-','-','-'],
['-','-','-','private','Trang Dinh Hanh','-','-','-'],
['-','-','-','private','Rio Jeon','-','-','-'],
['-','-','-','private','Khanh Linh Trinh','-','-','-'],
['-','-','-','private','올리브이','-','-','-'],
['-','-','-','private','Naoko Tsutsumizaki','-','-','-'],
['-','-','-','private','Benjamin Lee','-','-','-'],
['-','-','-','private','May May','-','-','-'],
['-','-','-','private','김애련','-','-','-'],
['-','-','-','private','Cappu Ccino','-','-','-'],
['-','-','-','private','GiPpeum Eunju Choi','-','-','-'],
['-','-','-','private','강동우','-','-','-'],
['-','-','-','private','김형진','-','-','-'],
['-','-','-','private','Exo Jang','-','-','-'],
['-','-','-','private','Aron Kim','-','-','-'],
['-','-','-','private','Saito Hideaki','-','-','-'],
['-','-','-','private','Howoon Chung','-','-','-'],
['-','-','-','private','Daejo Kim','-','-','-'],
['-','-','-','private','Ethan Xu','-','-','-'],
['-','-','-','private','Thai Hau','-','-','-'],
['-','-','-','private','Sangdam Sojang Kim','-','-','-'],
['-','-','-','private','Jun Junicorn','-','-','-'],
['-','-','-','private','Yujin Choi','-','-','-'],
['-','-','-','private','Jo Xia','-','-','-'],
['-','-','-','private','박선영','-','-','-'],
['-','-','-','private','Tina Yeung','-','-','-'],
['-','-','-','private','Yuko Kosako','-','-','-'],
['-','-','-','private','Tamai Katsunori','-','-','-'],
['-','-','-','private','Sera Kang','-','-','-'],
['-','-','-','private','Sandro Kim','-','-','-'],
['-','-','-','private','Morronga Kim','-','-','-'],
['-','-','-','private','오승준','-','-','-'],
['-','-','-','private','KKao Isk','-','-','-'],
['-','-','-','private','Nuri Kim Hogyu','-','-','-'],
['-','-','-','private','La Rose','-','-','-'],
['-','-','-','private','Nicholas Zhang','-','-','-'],
['-','-','-','private','곽환희','-','-','-'],
['-','-','-','private','Jongmin Terence An','-','-','-'],
['-','-','-','private','Michael Byungjun Lee','-','-','-'],
['-','-','-','private','Rachael JeongWon Kim','-','-','-'],
['-','-','-','private','Lan Gao','-','-','-'],
['-','-','-','private','Nero Kim','-','-','-'],
['-','-','-','private','Holim Choi','-','-','-'],
['-','-','-','private','최철호','-','-','-'],
['-','-','-','private','박경난','-','-','-'],
['-','-','-','private','Eunyoung Choi','-','-','-'],
['-','-','-','private','Suri Bae','-','-','-'],
['-','-','-','private','Ojko Tango','-','-','-'],
['-','-','-','private','Lino Rivas Jeon','-','-','-'],
['-','-','-','private','백종학','-','-','-'],
['-','-','-','private','Ju Yeon Lee','-','-','-'],
['-','-','-','private','Rhea Kim','-','-','-'],
['-','-','-','private','Hera Cho','-','-','-'],
['-','-','-','private','Rita Song','-','-','-'],
['-','-','-','private','임철환','-','-','-'],
['-','-','-','private','머루','-','-','-'],
['-','-','-','private','Jaen Kim','-','-','-'],
['-','-','-','private','김미경','-','-','-'],
['-','-','-','private','이민혁','-','-','-'],
['-','-','-','private','Alex Ha','-','-','-'],
['-','-','-','private','Seungae Lily Hahn','-','-','-'],
['-','-','-','private','Joan Ji-Hye Lee','-','-','-'],
['-','-','-','private','이윤진','-','-','-'],
['-','-','-','private','Jungrok Kim','-','-','-'],
['-','-','-','private','Yongkwang Cho','-','-','-'],
['-','-','-','private','Monica Kim','-','-','-'],
['-','-','-','private','Diego Xen','-','-','-'],
['-','-','-','private','Tulip TaeRang Joo','-','-','-'],
['-','-','-','private','Julia Wu','-','-','-'],
['-','-','-','private','강유은','-','-','-'],
['-','-','-','private','Marcelo Canaro','-','-','-'],
['-','-','-','private','이 보카','-','-','-'],
['-','-','-','private','Chris Kultur','-','-','-'],
['-','-','-','private','윤하정','-','-','-'],
['-','-','-','private','Yuji Choi','-','-','-'],
['-','-','-','private','루나','-','-','-'],
['-','-','-','private','Mia Ryan Tango','-','-','-'],
['-','-','-','private','Naro Kim','-','-','-'],
['-','-','-','private','Grey','-','-','-'],
['-','-','-','private','날개 탱고','-','-','-'],
['-','-','-','private','Monk Jung','-','-','-'],
['-','-','-','private','Zhang Vivian','-','-','-'],
['-','-','-','private','Grace Baoyu','-','-','-'],
['-','-','-','private','Jun Lee','-','-','-'],
['-','-','-','private','Eun Youl','-','-','-'],
['-','-','-','private','청주 에릭','-','-','-'],
['-','-','-','private','알파','-','-','-'],
['-','-','-','private','Meng Zhao','-','-','-'],
['-','-','-','private','Panda LU','-','-','-'],
['-','-','-','private','Victor Cho Hojong','-','-','-'],
['-','-','-','private','사띠','-','-','-'],
['-','-','-','private','Klaudia Bui Xuan','-','-','-'],
['-','-','-','private','Helen Won','-','-','-'],
['-','-','-','private','Allen Ma','-','-','-'],
['-','-','-','private','M Angela Romero Gragera','-','-','-'],
['-','-','-','private','Carol Liao','-','-','-'],
['-','-','-','private','Fukiko Hayashi','-','-','-'],
['-','-','-','private','Chowon Lee','-','-','-'],
['-','-','-','private','Hiroshi Yamao','-','-','-'],
['-','-','-','private','Eluca Kim','-','-','-'],
['-','-','-','private','Darby Yang','-','-','-'],
['-','-','-','private','Cande Nuño','-','-','-'],
['Asia','Taiwan','Taipei','private','Peggy Chen','veterinaria','KNOW','https://www.facebook.com/peggyvm'],
['-','-','-','private','Joo Han Gyu','-','-','-'],
['-','-','-','private','Jiyeon Choi','-','-','-'],
['-','-','-','private','Gigi Leung','-','-','-'],
['-','-','-','private','Hara Choi','-','-','-'],
['-','-','-','private','Rui Saito','-','-','-'],
['-','-','-','private','Violeta Arance','-','-','-'],
['-','-','-','private','Stephanie Teow','-','-','-'],
['-','-','-','private','Hong Kee Suk','-','-','-'],
['-','-','-','private','Elfin Chang','-','-','-'],
['-','-','-','private','Hsin-Da Lee','-','-','-'],
['-','-','-','private','LungLung James','-','-','-'],
['-','-','-','private','Junhee Bae','-','-','-'],
['-','-','-','private','Kyeong Hun Vincent Ryu','-','-','-'],
['-','-','-','private','陳東杰','-','-','-'],
['-','-','-','private','Fred Chee','-','-','-'],
['-','-','-','private','Laia Casals','-','-','-'],
['-','-','-','private','David Ng','-','-','-'],
['-','-','-','private','Nguyễn Thị Thanh Phương','-','-','-'],
['-','-','-','private','Cristopher Wibowo','-','-','-'],
['-','-','-','private','黃士弘','-','-','-'],
['-','-','-','private','Raymond Chu','-','-','-'],
['-','-','-','private','Zeng Yu','-','-','-'],
['-','-','-','private','Chris Han','-','-','-'],
['-','-','-','private','Hao Ran Shi','-','-','-'],
['-','-','-','private','Doan Kay','-','-','-'],
['-','-','-','private','Andrea Victoria','-','-','-'],
['-','-','-','private','Chung-yi Yoon','-','-','-'],
['-','-','-','private','Ha Thu','-','-','-'],
['-','-','-','private','Juhee Williamson','-','-','-'],
['-','-','-','private','Cheen Dancer','-','-','-'],
['-','-','-','private','Miae Tracy Kim','-','-','-'],
['-','-','-','private','Christina Gomez','-','-','-'],
['-','-','-','private','Robin MO','-','-','-'],
['-','-','-','private','Cinco EJ','-','-','-'],
['-','-','-','private','Ami Kim','-','-','-'],
['-','-','-','private','Lami Choi','-','-','-'],
['-','-','-','private','Thalia Jiyeon Yoo','-','-','-'],
['-','-','-','private','Peninsula Cho','-','-','-'],
['-','-','-','private','Johnny Jeon','-','-','-'],
['-','-','-','private','EunJae Lee','-','-','-'],
['-','-','-','private','Sasha HS','-','-','-'],
['-','-','-','private','Lena Eunjung Cho','-','-','-'],	
];