var publicPeople=[
['Asia','-','-','shopper','Yvette Ng','-','-','https://www.facebook.com/yvette.ng.9828/'],
['Asia','China','-','shopper','Sissy Simonet','-','-','https://www.facebook.com/myraliu61'],
['Asia','China','Henzhen','organizer','Aykut Kazanci','Luna Tango, Henzhen Tango Maraencuentro','-','https://www.facebook.com/aykut.kazanci/about'],
['Asia','China','Shanghai','organizer','Kai Wang','te amo tango lounge','-','-'],
['Asia','China','Shanghai','shopper','Weiwei QI','regina shoes','-','https://www.facebook.com/weiwei.qi.92'],
['Asia','Korea','-','dj','Alex Jonghwa Tangodj','-','-','-'],
['Asia','Korea','-','dj','Howoon Chung (El Loco)','-','-','-'],
['Asia','Korea','-','dj','Sangdam Sojang Kim (상담소장)','-','-','https://www.facebook.com/sangdamsojang'],
['Asia','Korea','-','dj','Cya Lu','-','-','-'],
['Asia','Korea','Busan','organizer','Gonny Jigon Park','Tango WK El Mar','-','https://www.facebook.com/jigon.park.739'],
['Asia','Korea','Busan','dj','Kang Seong Jin Ivan','-','-','https://www.facebook.com/seongjin.kang'],
['Asia','Korea','Changwon','organizer','Anna Choi','-','-','https://www.facebook.com/anna.choi.794009/'],
['Asia','Korea','Cheongju','organizer','Sofia Yeoreum','Studio Aura','-','https://www.facebook.com/sofia.yeoreum/'],
['Asia','Korea','Daegu','organizer','Nabi Nabi','-','-','https://www.facebook.com/nabi.nabi.397220'],
['Asia','Korea','Daejeon','organizer','Diego Ki','-','-','-'],
['Asia','Korea','Incheon','dj','Dopamine Henry','-','-','https://www.facebook.com/henry.wotton.357/'],
['Asia','Korea','Seoul','organizer','Aran Sunmi Kang','En Paz','-','https://www.facebook.com/aran.sunmikang/photos'],
['Asia','Korea','Seoul','writer','Beto Kim','-','-','https://www.facebook.com/byeoungjun.kim.9'],
['Asia','Korea','Seoul','artist','Eugene Bien','-','-','-'],
['Asia','Korea','Seoul','dj','Gianluca Seo','-','-','https://www.facebook.com/gianluca.seo/'],
['Asia','Korea','Seoul','shopper','Hyo-jung Oh','-','-','-'],
['Asia','Korea','Seoul','organizer','Kogsan Kyuho Kim','TangoLife','-','https://www.facebook.com/kogsan.kyuho.kim'],
['Asia','Korea','Seoul','organizer','Sophia Chung','Milonga Bulgeum - Onada','-','-'],
['Asia','Korea','Seoul','organizer','Youngsun Lee','Gusan Sunset Tango Maraton','-','https://www.facebook.com/youngsun.lee/about'],
['Asia','Korea','Seoul','dj','Geff Kim Taehwan','-','-','-'],
['Asia','Korea','Seoul','organizer','Hyun Jung Kim','Luminoso','-','https://www.facebook.com/luminoso.trees'],
['Asia','Korea','Seoul','artist','Aritta Angel','-','-','https://www.facebook.com/ArittaDongwooKim/about'],
['Asia','Korea','Suncheon','organizer','오승준 (bongbong)','-','-','https://www.facebook.com/profile.php?id=100002148016502'],
['Asia','Singapore','Singapore','organizer','Andrienne Tho','Singapore Tango Marathon','-','https://www.facebook.com/andrienne.tho/'],
['Asia','Singapore','Singapore','dj','Carman Chung','-','-','-'],
['Asia','Taiwan','-','organizer','Grace Liman Chan','-','-','-'],
['Asia','Taiwan','Taipei','organizer','Chanbee Bokchan Park','Tango Busan Weekend','-','https://www.facebook.com/bokchan.park'],
['Asia','Taiwan','Taipei','organizer','Sheen Chan','-','-','https://www.facebook.com/lovesheen'],
['Asia','Taiwan','Taipei','dj','陳東杰 (Tung-Chien Chen)','-','-','https://www.facebook.com/djchen0914/about'],
['Asia','Vietnam','Hanoi','organizer','Nguyen Phuong Ngoc (Moon Luna)','Luna Tango encuentro','-','https://www.facebook.com/ngocxiu2001'],
['Europe','-','-','dj','Tomasz Zabrzyjewski','-','-','-'],
['Europe','Barcelona','-','organizer','Alexis Quezada','-','-','-'],
['Europe','Czechia','-','organizer','Ondřej Tango','marathon praga','-','-'],
['Europe','Germany','-','dj','Alma Mia','-','-','-'],
['Europe','Germany','Munich','organizer','Sylvia Viñez','papusa','-','-'],
['Europe','Holand','Rotterdam','writer','Charlie Cool','-','-','https://www.facebook.com/charlie.cool.100'],
['Europe','Italy','-','dj','Ignacio Cavalieri','-','-','-'],
['Europe','Italy','Calgari','dj','Rita Rolando','-','-','-'],
['Europe','Lituania','Vilnius','organizer','Olga Makhno','-','-','https://www.facebook.com/olga.makhno.7/about'],
['Europe','Poland','Miedzyborow','organizer','Ernest Winkowski','el gordo','-','https://www.facebook.com/ernest.winkowski/about'],
['Europe','Spain','-','organizer,dj','David Reus','-','-','-'],
['Europe','Spain','-','artist,dj','Fernando Nahmijas','-','-','-'],
['Europe','Spain','-','artist','RoqueyGiselle Castellano GaticaLujan','-','-','-'],
['Europe','Spain','-','artist,organizer','Victoria Huang','-','-','-'],
['Europe','Spain','Bilbao','artist,organizer','BorjayChristina TangoBilbao','-','-','-'],
['Europe','Spain','Madrid','artist','Gisele Góngora','-','-','-'],
['Europe','Spain','Madrid','artist,dj','Carmen De La Rosa - Tango','-','-','-'],
['Europe','Spain','Madrid','artist','John Arbelaez','-','-','-'],
['Europe','Spain','Madrid','organizer','Loic Vix','la melange','-','-'],
['Europe','Spain','Madrid','artist','Sara Lorés Ara','-','-','-'],
['Europe','Spain','Madrid','artist','Teresa Yoldi Salinas','-','-','-'],
['Europe','Spain','San Sebastian','dj','Amaia Tango','-','-','-'],
['Europe','Spain','Sevilla','dj,organizer','Gaston Godoy','-','-','-'],
['Europe','Switzerland','-','organizer','Sia AliBaba','-','-','-'],

];